---



# -------------------------------------------------------------------
cora:      # 使用Cora数据集训练模型
# -------------------------------------------------------------------
    sparse:           false       # 是否使用稀疏数据
    random_state:     42          # 随机种子
    model:                        # 模型参数
        alpha:        0.2           # LeakyReLU斜率
        dropout:      0.5           # dropout比例
        num_heads:    8             # 多头注意力个数, 根据显存设置
        input_dim:    1433          # 节点特征维度
        hidden_dim:   8             # 隐层输出特征维度
        output_dim:   7             # 节点类别个数
    hyper:                        # 训练超参数
        lr:           0.005         # 优化器初始学习率
        epochs:       1000          # 训练轮次
        patience:     100           # 早停轮次
        weight_decay: 0.0005        # 优化器权重衰减



# -------------------------------------------------------------------
pubmed:    # 使用Pubmed数据集训练模型
# -------------------------------------------------------------------
    sparse:           true        # 是否使用稀疏数据
    random_state:     42          # 随机种子
    model:                        # 模型参数
        alpha:        0.2           # LeakyReLU斜率
        dropout:      0.7           # dropout比例
        num_heads:    8             # 多头注意力个数, 根据显存设置
        input_dim:    500           # 节点特征维度
        hidden_dim:   8             # 隐层输出特征维度
        output_dim:   3             # 节点类别个数
    hyper:                        # 训练超参数
        lr:           0.005         # 优化器初始学习率
        epochs:       1000          # 训练轮次
        patience:     100           # 早停轮次
        weight_decay: 0.0005        # 优化器权重衰减



# -------------------------------------------------------------------
citeseer:  # 使用Citeseer数据集训练模型
# -------------------------------------------------------------------
    sparse:           false       # 是否使用稀疏数据
    random_state:     42          # 随机种子
    model:                        # 模型参数
        alpha:        0.2           # LeakyReLU斜率
        dropout:      0.7           # dropout比例
        num_heads:    8             # 多头注意力个数, 根据显存设置
        input_dim:    3703          # 节点特征维度
        hidden_dim:   8             # 隐层输出特征维度
        output_dim:   6             # 节点类别个数
    hyper:                        # 训练超参数
        lr:           0.005         # 优化器初始学习率
        epochs:       1000          # 训练轮次
        patience:     100           # 早停轮次
        weight_decay: 0.0005        # 优化器权重衰减



...